name: Tests

on: [push, pull_request]

jobs:
  Linter:
    name: Jest Test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Set up Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install required dependency for node
        run: |
          yarn install
      - name: Run Jest Test
        run: |
          yarn jest
